# -*- coding: utf-8 -*-
"""ClaseS5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aFMX3nbCFomQrKWkFionnAJJJt9BOsme
"""

!pip install matplotlib

!pip install numpy

from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt

x = np.array([2,3,4,4,5,6,6,7,7,8,10,10])   # Notas Física
y = [1,3,2,4,4,4,6,4,6,7,9,10]    # Notas Matemática

regresion_FisMat = LinearRegression()      # Instancia del objeto LinearRegression
regresion_FisMat.fit(x.reshape(-1,1), y)  # Instrucción del modelo a partir de los datos x,y

print('w = ' + str(regresion_FisMat.coef_) + ', b = ' + str(regresion_FisMat.intercept_))

# Predicción con x= np.array([7.5])
nuevo_x = np.array([7.5])
prediccion = regresion_FisMat.predict(nuevo_x.reshape(-1,1))
print(prediccion)

# Predicción con x= np.array([3])
nuevo_x = np.array([3])
prediccion = regresion_FisMat.predict(nuevo_x.reshape(-1,1))
print(prediccion)

# Predicción con x= np.array([9.5])
nuevo_x = np.array([9.5])
prediccion = regresion_FisMat.predict(nuevo_x.reshape(-1,1))
print(prediccion)